import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Mem's Transcript | By Cabrel KL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.png" type="image/png" />
      </head>
      <body
      >
        {children}
      </body>
    </html>
  );
}
